model:
  users:
    name:
      maximum: 50
    email:
      maximum: 255
    password:
      minimum: 6
session:
  create:
    remember_me: 1
gravatar:
  size: 80
  for_user: 50
paginate:
  per_page: 15
