model:
  users:
    name:
      maximum: 50
    email:
      maximum: 255
    password:
      minimum: 6
session:
  create:
    remember_me: 1
gravatar:
  size: 80
  for_user: 50
paginate:
  per: 15
timeout:
  reset_sent: 2
microposts:
  content:
    maximum: 140
micropost_size: 50
picture: 5
size_in_mega: 5
picture_height: 400
picture_width: 400
accept_type: "image/jpeg,image/gif,image/png"
